import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import Providers from "./providers";

import Header from "./components/layout/Header";
import Footer from "./components/layout/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const avenir = localFont({
  src: [
    {
      path: "../../public/fonts/AvenirLTStd55Roman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/AvenirBook.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/AvenirBlack.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-avenir-local",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${avenir.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Header />

          <Providers>

              {children}
              
          </Providers>
       
        
        <Footer />

      </body>

    </html>
  );
}
